/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.2/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application

    // Apply the Spotless plugin for code formatting.
    id("com.diffplug.spotless") version "7.1.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.textanalyzr.tool"
    // Set the application name
    applicationName = "TextAnalyzr"
    // Set the base name for the application
    applicationDefaultJvmArgs = listOf("-Dapp.name=TextAnalyzr")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

// Configure the Spotless plugin.
spotless {
    java {
        target("src/**/*.java")
        googleJavaFormat()
    }
}

// Specify the version of the project
version = "0.1.0"

// Configure the JAR manifest
tasks.jar {
    manifest {
        attributes(
            "Implementation-Title" to "TextAnalyzr",
            "Implementation-Version" to version,
            "Main-Class" to "com.textanalyzr.tool"
        )
    }

    archiveBaseName.set("textanalyzr")
}